version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: verity-loop
    main: ./cmd/verity-loop
    binary: verity-loop
    goos:
      - darwin
    goarch:
      - arm64

archives:
  - id: verity-loop
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

